### ISSUE TITLE
Круг не круглый, плюс не по центру

### ISSUE THREAD

**Issue by zunhdev** [alenasova/task-3#3]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/2992696/41561060-8bad2c96-7351-11e8-9cdc-699de09d4281.png">

**Comment by alenasova** [comment]
У меня с ним творится что-то странное. Вроде был по центру, потом полез вниз, я добавила паддинг. Сейчас убрала - но все равно не уверена, что в центре. Хотя, кажется, что должен быть. Учитывая стили.
