### ISSUE TITLE
Проценты везде не как в макете. Должны быть сдвинуты вверх и меньше.

### ISSUE THREAD

**Issue by zunhdev** [alenasova/task-3#5]
<img width="118" alt="image" src="https://user-images.githubusercontent.com/2992696/41561220-f2019a40-7351-11e8-8d0e-f2d2df009853.png">

**Comment by alenasova** [comment]
done

**Comment by zunhdev** [comment]
Не везде поправлено.

**Comment by alenasova** [comment]
а, поняла.

**Comment by alenasova** [comment]
сделала. Только не понимаю, почему у меня не получилось таким же способом, как в блоке с операционными системами.
Пришлось другим свойством. Может, даже логичнее)) Но, тем не менее, вопрос мучает

**Comment by zunhdev** [comment]
Потому что элементы в разным значением свойства display ведут себя по-разному. Там, где операционные системы display: block, и vertical-align не работает. Там, где прогресс-бары, display: inline-block, и там работает vertical-align. А еще можно что-то типа
`
position: relative;
top: -50%;
font-size: 50%;
`

И по-прежнему не везде на странице сделано!

**Comment by alenasova** [comment]
Да, точно. Сделала. Буду тренировать внимательность.
Я понимаю, что с разными значениями display элементы ведут себя по-разному. Но не понял, почему в первом случае (с операционками) получилось сделать отступом от нижней границы родительского элемента, а добавив тот же класс спан-у во втором и третьем случае, значок уехал вверх вместе с цифровым значением
