### ISSUE TITLE
При наведении двухпиксельный разделитель пунктов становится однопиксельным

### ISSUE THREAD

**Issue by zunhdev** [alenasova/task-3#6]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/2992696/41561277-22d68978-7352-11e8-8447-b061e98d6e90.png">

**Comment by alenasova** [comment]
Не могу понять, почему так. Там не при наведении меняется бордер, да и вообще там не бордер, а марджин-боттом. И почему-то (я тупарь) у sunday и statistics этот марджин меньше, чем у остальных

**Comment by alenasova** [comment]
<div class="wrapper background-dark-gray">
                        <div class="group group-left red-day">
                            <div class="">SUN</div>
                            <div class="light-gray group-left">30/06</div>
                        </div>
                        <div class="group group-right">
                            <div class="center">29<img src="img/sun-g.png" class="icon-mini"></div> 
                        </div>
                    </div>
                    <div class="wrapper background-dark-gray">
                        <div class="group group-left red-day">
                            <div class="">MON</div>
                            <div class="light-gray group-left">01/07</div>
                        </div>
                        <div class="group group-right">
                            <div class="center">29<img src="img/sun-g.png"  class="icon-mini"></div>
                        </div>
                    </div>
Ну одинаково же все у sun и mon? Нет?

**Comment by alenasova** [comment]
посмотрела через "инструменты разработчика" - все равно не понимаю, везде стоит марджин-боттом 1px

**Comment by zunhdev** [comment]
Не знаю, сейчас вроде бы нормально. Закрываем.
